version: "3.8" # Version of the Docker Compose file format

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # Use a custom redis.conf for configuration
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  # Start Redis with the custom configuration

  redisinsight:
    image: redis/redisinsight:2.54
    container_name: redisinsight
    restart: always
    ports:
      - '5540:5540'
    depends_on:
      - redis
    volumes:
      - redisinsight:/db

volumes:
  redisinsight: