version: "3.8"

services:
  redis:
    image: redis:7.4.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]  # Bind to all interfaces
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight:2.54
    container_name: redisinsight
    restart: always
    ports:
      - '5540:5540'
    depends_on:
      - redis
    volumes:
      - redisinsight:/db
    networks:
      - app-network

  app:
    build:
      context: .  # Docker context, assuming Dockerfile is in the root
    container_name: ardoco-rest-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker # select active profile in spring
    networks:
      - app-network

volumes:
  redisinsight:

networks:
  app-network:
    driver: bridge
