services:
  redis:
    image: redis
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    restart: always
    ports:
      - '127.0.0.1:5540:5540'
    depends_on:
      - redis
    volumes:
      - ./redisinsight:/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ardoco/rest
    container_name: ardoco-rest-api
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ~/.m2:/root/.m2
#      - ../REST:/build
#      - ../REST/target:/target

networks:
  app-network:
    driver: bridge
